"""0002 migration

Revision ID: 0d465cc09a60
Revises: 61d4b1979617
Create Date: 2023-11-17 14:14:44.998469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d465cc09a60'
down_revision: Union[str, None] = '61d4b1979617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type', sa.Column('itemType', sa.String(), nullable=True))
    op.add_column('item_type', sa.Column('description', sa.String(), nullable=True))
    op.add_column('item_type', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_item_type_description'), 'item_type', ['description'], unique=False)
    op.create_index(op.f('ix_item_type_itemType'), 'item_type', ['itemType'], unique=False)
    op.create_foreign_key(None, 'item_type', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_type', type_='foreignkey')
    op.drop_index(op.f('ix_item_type_itemType'), table_name='item_type')
    op.drop_index(op.f('ix_item_type_description'), table_name='item_type')
    op.drop_column('item_type', 'item_id')
    op.drop_column('item_type', 'description')
    op.drop_column('item_type', 'itemType')
    # ### end Alembic commands ###
